### ISSUE TITLE
Question: why is the npm package not a shim?

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/denokv#51]
There is already https://github.com/denoland/node_shims which provides all the Deno APIs in Node.

Could you explain why you decided against integrating the npm package `@deno/kv` into the existing project? It would be a natural fit, no?

Do you have plans to add it there as a re-export?

**Comment by igorzi** [comment]
https://github.com/denoland/denokv repo is dedicated to projects related to Deno KV, which makes it a natural fit for KV npm package. There are no plans to move it to https://github.com/denoland/node_shims.
