### ISSUE TITLE
How to delete data in Kv

### ISSUE THREAD

**Issue by James-Leste** [denoland/denokv#65]
For example I have a list of Kv value stored in my local machine stored like this
```javascript
    //create a new UID for todo item.
    item.id = crypto.randomUUID();
    const kv = await Deno.openKv();
    await kv.set(["items", item.id], todo);
```
All I found is 
> [delete](https://deno.land/api@v1.39.2?unstable=true&s=Deno.Kv&p=prototype.delete)(key: [KvKey](https://deno.land/api?s=Deno.KvKey&unstable=)): Promise<void>
> Delete the value for the given key from the database. If no value exists for the key, this operation is a no-op.

How to delete all the data inserted into the database without explicitly providing all the UIDs.

**Comment by losfair** [comment]
You could list all the keys and delete them:

```ts
const promises = [];
for await (const entry of kv.list({ prefix: [] })) {
  promises.push(kv.delete(entry.key));
}
await Promise.all(promises);
```

**Comment by James-Leste** [comment]
It works for me, thank you so much. I am wondering if there is a need for writing a function for batch deletion.

**Comment by igorzi** [comment]
Yes, you can use `kv.atomic()` to batch many deletes into the same transaction (limit is 1000 keys per transaction).
