### ISSUE TITLE
NPM: Wrap the Deno KV API if available

### ISSUE THREAD

**Issue by RuiNtD** [denoland/denokv#67]
The NPM package should just re-export the values of Deno if Deno's native KV API is available, so that Node projects using `@deno/kv` can be more easily ported to Deno.

**Comment by johnspurlock-skymethod** [comment]
It does: https://github.com/denoland/denokv/blob/a5ae69f1dd58283ae124771e0d136a6b1815d7a5/npm/src/npm.ts#L53

**Comment by RuiNtD** [comment]
Huh... I tried this and for some reason it gave me an error in the SQLite NPM package. Maybe I just forgot to enable unstable-kv

**Comment by igorzi** [comment]
Closing. @RuiNtD please reopen if this is still an issue.
