### ISSUE TITLE
 Incomplete Value Type Support in Rust Crates for Deno KV

### ISSUE THREAD

**Issue by beingminimal** [denoland/denokv#68]
We are using deno_kv and denokv_proto both crates to interact with Deno KV from Rust. While key types are supported as expected, the available value types in the Rust crates appear to be limited compared to those documented for Deno KV itself.

Official Deno KV Documentation
[Supported Value Types](https://docs.deno.com/deploy/kv/manual/key_space#values)

Rust Crate Documentation
[Supported Key Types](https://docs.rs/denokv_proto/0.7.0/denokv_proto/enum.KeyPart.html) 
[Supported Value Types](https://docs.rs/denokv_proto/0.7.0/denokv_proto/enum.KvValue.html) 

**Request**
Please consider expanding the value type support in the Rust crates to align with the Deno KV documentation.
If there are specific reasons for the current limitations, please provide clarification and potential workarounds.

**Comment by nhrones** [comment]
I think the list in the Deno kv docs is actually V8 types and documented in Rust as, V8(Vec<u8>), but I may be wrong!

**Comment by igorzi** [comment]
`KvValue::V8` is being deprecated. `KvValue::V8` is how all Javascript values are serialized. As far as Rust `denokv` crate is concerned, these are opaque `Vec<u8>` values. If you want to be able to inspect/modify the V8 Javascript objects from Rust, please take a look at https://github.com/denoland/v8_valueserializer (also used in this repo).

**Comment by beingminimal** [comment]
> `KvValue::V8` is being deprecated. `KvValue::V8` is how all Javascript values are serialized. As far as Rust `denokv` crate is concerned, these are opaque `Vec<u8>` values. If you want to be able to inspect/modify the V8 Javascript objects from Rust, please take a look at https://github.com/denoland/v8_valueserializer (also used in this repo).

@igorzi thank you so much for your help, it's working fine now and KV values are also visible in KV console.
and so i am closing this issue.
