### ISSUE TITLE
null versionstamp checks always failed (nodejs)

### ISSUE THREAD

**Issue by codehz** [denoland/denokv#85]
version: 0.8.1 (platform: mac)
example:

```js
import { openKv } from "@deno/kv";
import { unlink } from "node:fs/promises";

try {
  await unlink("test.db");
} catch {}
const kv = await openKv("test.db", {});
const key = ["test"];
const empty = await kv.get(key);
const result = await kv.atomic().check(empty).commit();
console.log(result);
```

always got ok: false

but the docs say:
> A check with a null versionstamp checks that the key-value pair does not currently exist in the KV store.

**Comment by JakobHock** [comment]
I am experiencing this aswell.
Node: 22.2.0

**Comment by codehz** [comment]
After capture the packet, I found the reason

this is what I got from node version (hex) (AtomicWrite request)
0A 14 0A 06 02 74 65 73 74 00 12 0A 00 00 00 00 00 00 00 00 00 00
this is deno version (hex)
0a 08 0a 06 02 74 65 73 74 00
